config/routes.rb
Dmockcrazy2::Application.routes.draw do
  devise_for :admins

  devise_for :users

  resources :candidates

  match  'vote' => 'vote#index'
  post 'vote/submit'
  match 'results' => 'results#index'

  root :to => 'home#index'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/models/candidate.rb
class Candidate < ActiveRecord::Base
  attr_accessible :name

  validates :name,  :presence => true

  has_many :votes,
           :dependent => :destroy

  # Clear votes records before destroy
  before_destroy :clear_votes

  protected
  def clear_votes
    votes.clear
  end
end

app/models/user.rb
class User < ActiveRecord::Base

  has_one :vote
end

app/models/vote.rb
class Vote < ActiveRecord::Base

  belongs_to :candidate
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/candidates_controller.rb
class CandidatesController < ApplicationController

  before_filter :authenticate_admin! #admins only

  # GET /candidates
  # GET /candidates.json
  def index
    @candidates = Candidate.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @candidates }
    end
  end

  # GET /candidates/1
  # GET /candidates/1.json
  def show
    @candidate = Candidate.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @candidate }
    end
  end

  # GET /candidates/new
  # GET /candidates/new.json
  def new
    @candidate = Candidate.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @candidate }
    end
  end

  # GET /candidates/1/edit
  def edit
    @candidate = Candidate.find(params[:id])
  end

  # POST /candidates
  # POST /candidates.json
  def create
    @candidate = Candidate.new(params[:candidate])

    respond_to do |format|
      if @candidate.save
        format.html { redirect_to @candidate, notice: 'Candidate was successfully created.' }
        format.json { render json: @candidate, status: :created, location: @candidate }
      else
        format.html { render action: "new" }
        format.json { render json: @candidate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /candidates/1
  # PUT /candidates/1.json
  def update
    @candidate = Candidate.find(params[:id])

    respond_to do |format|
      if @candidate.update_attributes(params[:candidate])
        format.html { redirect_to @candidate, notice: 'Candidate was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @candidate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /candidates/1
  # DELETE /candidates/1.json
  def destroy
    @candidate = Candidate.find(params[:id])
    @candidate.votes.clear
    @candidate.destroy

    respond_to do |format|
      format.html { redirect_to candidates_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  # GET /candidates
  # GET /candidates.json
  def index
    respond_to do |format|
      format.html # index.html.erb
    end
  end
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
  def index
    @candidates = Candidate.all

    @total_vote = Vote.count

    #Find out who is in the lead
    @winner = @candidates.first
    runner_up = @candidates.second
    @candidates.each do |candidate|
      if candidate.votes.count > @winner.votes.count
        runner_up = @winner
        @winner = candidate
      end
    end
    if @total_vote == 0 or @winner.votes.count == runner_up.votes.count
      @winner = nil
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @candidates }
    end
  end
end

app/controllers/vote_controller.rb
class VoteController < ApplicationController

  before_filter :authenticate_user! #users only

  # GET /vote
  # GET /vote.json
  def index
    @candidates = Candidate.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @candidates }
    end
  end

  def submit
    #candidate = Candidate.find(params[:id])
    @vote = Vote.new

    @candidate = Candidate.find(params[:id])
    @vote = @candidate.votes.create
    current_user.vote = @vote

    respond_to do |format|
      format.html { redirect_to results_path, notice: 'Your vote was recorded!' }
      format.json { render json: vote }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/candidates_helper.rb
module CandidatesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/helpers/vote_helper.rb
module VoteHelper
end

app/views/candidates/_form.html.erb
<%= form_for(@candidate) do |f| %>
  <% if @candidate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@candidate.errors.count, "error") %> prohibited this candidate from being saved:</h2>

      <ul>
      <% @candidate.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/candidates/edit.html.erb
<h1>Editing candidate</h1>

<%= render 'form' %>

<%= link_to 'Show', @candidate %> |
<%= link_to 'Back', candidates_path %>

app/views/candidates/index.html.erb
<h1>Listing candidates</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Votes</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @candidates.each do |candidate| %>
  <tr>
    <td><%= candidate.name %></td>
    <td><%= candidate.votes.count %></td>
    <td><%= link_to 'Show', candidate %></td>
    <td><%= link_to 'Edit', edit_candidate_path(candidate) %></td>
    <td><%= link_to 'Destroy', candidate, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Candidate', new_candidate_path %>

app/views/candidates/new.html.erb
<h1>New candidate</h1>

<%= render 'form' %>

<%= link_to 'Back', candidates_path %>

app/views/candidates/show.html.erb
<p>
  <b>Name:</b>
  <%= @candidate.name %>
</p>

<p>
  <b>Votes:</b>
  <%= @candidate.votes.count %>
</p>


<%= link_to 'Edit', edit_candidate_path(@candidate) %> |
<%= link_to 'Back', candidates_path %>

app/views/home/index.html.erb
<h1>Welcome</h1>

<p>
      In the millenia since the invention of the Internet, users have wondered can I vote online and will it be secure?
</p>
<p>We have answered this question with a resounding Yes and then No.<br><strong>Introducing D-Mock-Crazy, the first ever completely insecure online voting system.  </strong></p>
<p>Key Features</p>
<ol>
  <li>
    We thought about using state of the art 2048 bit military grade SHA salted encryption.<br> But then we asked ourselves, "why bother?".
  </li>
  <li>
    No paper trail, unless you want to use your own printer.
  </li>
  <li>
    Admins can delete candidates during an election
  </li>
</ol>
<p>
  <h3>Instructions</h3>
  Use the above links to <%= link_to "vote", vote_path %> (requires <%= link_to "user registration", new_user_registration_path %>) or <%= link_to "configure an election", candidates_path %> (requires <%= link_to "admin registration", new_admin_registration_path %>).
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dmockcrazy</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="wrapper">

  <div id="header">
    <a href="<%= root_url %>"><img src="<%= root_url %>assets/logo.png"></a>
  </div><!-- #header-->

  <div id="nav">
    <div id="nav-ribbon-left"></div>
    <div id="nav-ribbon-right"></div>

    <ul>
      <li>
        <% #link_to 'Admin', elections_path %>
      </li>
      <li>
        <%= link_to 'Vote!', vote_path %>
      </li>
      <li>
        <%= link_to 'Results', results_path %>
      </li>
      <li>
        <%= link_to "Admin", candidates_path %>
      </li>
      <li>
        <% if user_signed_in? %>
            <%= link_to "Sign Out", destroy_user_session_path, :method => :delete %>
        <% end %>
      </li>
      <% if admin_signed_in? %>
      <li>
            <%= link_to "Sign Out As Admin", destroy_admin_session_path, :method => :delete %>
      </li>
      <% end %>
    </ul>
  </div><!-- #nav-->



  <div id="content">
    <p class="notice" id="notice"><%=  notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </div><!-- #content-->

</div><!-- #wrapper -->

<!--<div id="footer">
</div>--><!-- #footer -->
</body>
</html>

app/views/results/_chart.html.erb
<%
   colors = [ "red", "blue", "purple", "orange", "green"]
%>

<script type="text/javascript">
    var chart;

    var chartData = [
        <% @candidates.each_with_index do |candidate, index| %>
        {
        candidate: "<%= candidate.name %>",
        votes: <%= candidate.votes.count %>,
        color: "<%= colors[index % (colors.length)] %>"
        }
        <% if candidate != @candidates.last %>,<% end  %>
        <% end %>
    ];

    AmCharts.ready(function () {
        // SERIAL CHART
        chart = new AmCharts.AmSerialChart();
        chart.dataProvider = chartData;
        chart.categoryField = "candidate";
        chart.startDuration = 1;

        // AXES
        // category
        var categoryAxis = chart.categoryAxis;
        categoryAxis.labelRotation = 45; // this line makes category values to be rotated
        categoryAxis.gridAlpha = 0;
        categoryAxis.fillAlpha = 1;
        categoryAxis.fillColor = "#FAFAFA";
        categoryAxis.gridPosition = "start";

        // value
        var valueAxis = new AmCharts.ValueAxis();
        valueAxis.dashLength = 5;
        valueAxis.title = "Total Votes"
        valueAxis.axisAlpha = 0;
        chart.addValueAxis(valueAxis);

        // GRAPH
        var graph = new AmCharts.AmGraph();
        graph.valueField = "votes";
        graph.colorField = "color";
        graph.balloonText = "[[category]]: [[value]]";
        graph.type = "column";
        graph.lineAlpha = 0;
        graph.fillAlphas = 1;
        chart.addGraph(graph);

        // WRITE
        chart.write("chart-div");
    });
</script>

<div id="chart-div"></div>

app/views/results/index.html.erb


<h1>
  <%if @winner%>
      <%=  @winner.name %> is in the lead!
  <%else%>
      No one is leading yet!
  <%end%>
</h1>

<% if current_user and current_user.vote %>
    <h3>You voted for <%= current_user.vote.candidate.name %></h3>
<% end %>

<div id="table-with-graph">
  <%= render 'chart' %>

    <table>
      <tr>
        <th>Name</th>
        <th>Votes</th>
        <th>% Vote</th>
      </tr>
      <tfoot>
      <tr>
        <td>Total</td>
        <td><%= @total_vote %></td>
        <td>100.00%</td>
      </tr>
      </tfoot>

      <% @candidates.each do |candidate| %>
          <tr>
            <td><%= candidate.name %></td>
            <td><%= candidate.votes.count %></td>
            <td><%= number_to_percentage(candidate.votes.count * 100 / (@total_vote * 1.0),:precision => 2) %></td>
          </tr>
      <% end %>
    </table>

</div>



app/views/vote/_form.html.erb
<%= form_tag("/vote/submit", :method => "post") do %>
    <% @candidates.each do |candidate| %>
        <div class="candidate_option">
          <%= label_tag candidate.name.camelcase %>
          <%= radio_button_tag("id", candidate.id) %>
        </div>
    <% end %>
    <br/>
    <div class="actions">
      <%= submit_tag "Vote" %>
    </div>
<% end %>

app/views/vote/index.html.erb
<h1>Vote!</h1>

<% if current_user.vote %>
    <h3>You've already voted for <%= current_user.vote.candidate.name %></h3>
    <h5>(You can always register a user account and vote again!)</h5>
<% else %>
    <% if @candidates.count > 0 %>
        <%= render 'form' %>
    <% else %>
        <h3>No Candidates Defined</h3>
    <% end %>
<% end %>